### ISSUE TITLE
진교수님과 줌 미팅

### ISSUE THREAD

**Issue by MyungAe** [UneducatedCoders-2022-capstone/docs#2]
진영택 교수님과 줌 미팅 있습니다.

220216 수요일 저녁 7시까지 아래 내용 준비해서 참석 바랍니다.

### 1. 프로젝트 목적 (매우 중요함)

- 왜 이 프로젝트를 진행하는가? 비지니스 관점과 기술적인 관점

- 우리 프로젝트와 유사한 과제(논문, 특허, 상용제품)가 있는가? 있다면 차별점은 무엇인가?

### 2. 프로젝트 내용

- 프로젝트에서 수행할 기능(서비스)은 무엇인가? 

### 3. 필요기술과 현재 수준

- 전체적인 구현환경: 서버, 프로그래밍 언어, UI 등 

- 팀원들의 수준은? 어느 정도 공부해야 하는가?

**Comment by sungbbang** [comment]
확인했습니다.
