### ISSUE TITLE
노션에 기록한 스터디를 위키로 옮겨주세요.

### ISSUE THREAD

**Issue by MyungAe** [UneducatedCoders-2022-capstone/docs#5]
자바스크립트, 리액트 스터디 내용을 위키로 옮겨주세요.

감사합니다.

참고 : https://hbase.tistory.com/223

**Comment by 0-ROK** [comment]
노션에 있던 자바스크립트 스터디 기록, 깃허브에 업로드했습니다.
감사합니다.
