### ISSUE TITLE
유저스토리 회의 참여 부탁드립니다.

### ISSUE THREAD

**Issue by MyungAe** [UneducatedCoders-2022-capstone/docs#6]
안녕하세요. 팀원 여러분

3월 7일, 각자 작성한 유저스토리를 바탕으로 베스트 시나리오를 작성하고자 합니다.

가능한 시각은 아래 첨부해주시기 바랍니다.

감사합니다.

**Comment by sungbbang** [comment]
오후 6시 이후 가능합니다.

**Comment by 0-ROK** [comment]
오후 1시~6시에 시간 가능합니다. 화요일 6시 이후는 어떠신가요?

**Comment by MyungAe** [comment]
화요일 6시 이후 가능합니다. 

@sungbbang 가능하신가요?

**Comment by sungbbang** [comment]
가능합니다.

**Comment by MyungAe** [comment]
회의 결과, 유저스토리는 @MyungAe 작성 후 교수님과 상의하도록 결정되었습니다.
